### ISSUE TITLE
Turn this into a gh-pages website

### ISSUE THREAD

**Issue by stvnrlly** [DCgov/civic.json#3]
Here's the structure that would be useful:

index.html - intro, reasons behind the standard, how to contribute
|-- how-to-implement.html
|-- specification.html
|-- schema.json

**Comment by emanuelfeld** [comment]
By 'how to implement' you mean things like adding the file to your repo?

**Comment by stvnrlly** [comment]
Yep! And could also include links to validators/builders, wherever they may live (this could also be a good location for those, if you want)

**Comment by emanuelfeld** [comment]
OK, haven't put up the spec page yet, but there's a start here http://open.dc.gov/civic.json/

**Comment by emanuelfeld** [comment]
Also need a non stupid tag line

**Comment by emanuelfeld** [comment]
And likely a slightly different naming convention to make clear that this is an extension of the original civic.json.
